---
- hosts: all
  become: true
  tasks:

  - name: full upgrade
    apt:
      update_cache=true
      upgrade=full

  - name: set cmd path 
    set_fact:
      cmdline_txt_path: /boot/cmdline.txt

  - include_tasks: cmdline.yaml
    vars:
      key: cgroup_enable
      value: cpuset
      update: false

  - include_tasks: cmdline.yaml
    vars:
      key: cgroup_enable
      value: memory
      update: false

  - include_tasks: cmdline.yaml
    vars:
      key: cgroup_memory
      value: 1
      update: true

  - name: reboot
    reboot:
      connect_timeout: 60