---
- hosts: all
  become: true
  tasks:

  - name: full upgrade
    apt:
      update_cache=true
      upgrade=full

  - include_tasks: enable_cgroup.yaml

  - name: reboot
    reboot:
      connect_timeout: 60