---
- hosts: addresses
  gather_facts: true
  roles:
    - role: prereq
      become: true

- hosts: basics
  gather_facts: true
  handlers: # TODO deprecated
    - include: roles/prereq/handlers/main.yml
  roles:
    - role: node_exporter
      become: true
    - role: cgroupv2
      become: true
    - role: firewalld
      become: true
    - role: packages
      become: true

- hosts: worker-nodes
  gather_facts: true
  roles:
    - role: longhorn
      become: true