---
#https://stackoverflow.com/a/58859781
- name: "Update hostname"
  hostname:
    name: "{{ new_hostname }}"
  notify: reboot

- name: Update hosts file
  become: true
  ansible.builtin.template:
    src: hosts.j2
    dest: "/etc/hosts"
    mode: 0644
  vars:
    content: "{{ new_hostname }}"

- name: Disable initial-setup
  ansible.builtin.systemd:
    name: initial-setup
    enabled: no

- name: Update kernel arguments
  become: true
  shell: grubby --args="delayacct" --update-kernel=ALL
  notify: reboot