---
- name: Uninstall cockpit
  ansible.builtin.dnf:
    name: cockpit,cockpit-bridge,cockpit-networkmanager,cockpit-packagekit,cockpit-selinux,cockpit-storaged,cockpit-system,cockpit-ws
    state: absent
    autoremove: yes