---
- name: Enable CPU and CPUSet
  ansible.builtin.shell: |
    echo "+{{ item }}" >> /sys/fs/cgroup/cgroup.subtree_control
    grep "{{ item }}" /sys/fs/cgroup/cgroup.subtree_control -q
  loop:
    - cpu
    - cpuset

- name: Create /etc/systemd/system/user@.service.d directory
  file:
    path: /etc/systemd/system/user@.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Add Delegate
  template:
    src: delegate.conf.j2
    dest: "/etc/systemd/system/user@.service.d/delegate.conf"
  become: true

- name: Get user id
  shell: 'id -u {{ created_user }}'
  register: user_id
  changed_when: false

- name: Create slice file
  template:
    src: user-slice.conf.j2
    dest: "/etc/systemd/system/user-{{ user_id.stdout }}.slice"
  become: true

- name: Enable user slice
  systemd:
    state: started
    name: user-{{ user_id.stdout }}.slice
    enabled: yes
    daemon_reload: yes
  become: true