---
- name: Enable CPU and CPUSet
  ansible.builtin.shell: |
    echo "+{{ item }}" >> /sys/fs/cgroup/cgroup.subtree_control
    grep "{{ item }}" /sys/fs/cgroup/cgroup.subtree_control -q
  loop:
    - cpu
    - cpuset