---

- name: Create {{ mount_point }} directory
  ansible.builtin.file:
    path: "{{ mount_point }}"
  become: true

- name: Unmount
  mount:
    path: "{{ mount_point }}"
    state: unmounted

- name: Create a ext4 filesystem on {{ disk_device }} and check disk blocks
  community.general.filesystem:
    fstype: btrfs
    force: true
    dev: "{{ disk_device }}"

- name: Mount Btrfs partition on {{ mount_point }}
  ansible.posix.mount:
    src: "{{ disk_device }}"
    path: "{{ mount_point }}"
    fstype: btrfs
    opts: defaults
    state: mounted