---

# - name: Enable default node_exporter port traffic
#   ansible.posix.firewalld:
#     zone: FedoraServer
#     service: prometheus-node-exporter
#     permanent: true
#     immediate: true
#     state: enabled


- name: Disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: no