---
- name: Create pi user
  user:
    name: pi
    state: present
    groups: wheel
    append: yes

- name: Set authorized key for user pi copying it from current user
  ansible.posix.authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"