---
- name: Create user
  user:
    name: "{{ created_user }}"
    state: present
    groups: wheel
    append: yes

- name: Set authorized key for user copying it from current user
  ansible.posix.authorized_key:
    user: "{{ created_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Passwordless sudoer
  become: true
  ansible.builtin.template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/00-pi"
    mode: 0440
  vars:
    content: "{{ new_hostname }}"